## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/dep_config.yaml

DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: Depression Symptoms
TraitBlurb: "***Broad Depression Symptons*** [Howard et al 2018](https://doi.org/10.1038/s41467-018-03819-3):
  Using up to 322,580 UK Biobank participants, broad depression was based on
  self-reported help-seeking behaviour for mental health difficulties from either
  a general practitioner or psychiatrist."
TraitCode: dep
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
