## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/ldl_config.yaml

DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: LDL Cholesterol
TraitBlurb: "***LDL Cholesterol*** [Willer et al Nat Genet 2013](https://www.nature.com/articles/ng.2797):
  To identify new loci and refine known loci influencing these lipids, we examined
  188,577 individuals using genome-wide and custom genotyping arrays. We identify
  and annotate 157 loci associated with lipid levels at P < 5 × 10−8, including
  62 loci not previously associated with lipid levels in humans."
TraitCode: ldl
TraitClump: None
DataOut: 2_DerivedData/
NbDistribution: 20000
Pthreshold: [5e-6, 5e-8]
Cache: TRUE
