## Config file for MR analysis
# snakemake -s mr_dos.smk --configfile 3_Scripts/mr_config/ab42_load_config.yaml

#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
Pleitropy: 'FALSE'

TraitName_1: "CSF Ab42"
TraitBlurb_1: "***CSF Ab42*** (Deming et al 2017): A GWAS
  of CSF AB42, ptau and tau levels (pg/mL) was conducted in 3,146 participants.
  Participants were of Eurpean ancestry."
TraitCode_1: ab42
TraitClump_1: None

TraitName_2: Alzheimer’s disease
TraitBlurb_2: "***Late Onset Alzheimer’s disease*** (Lambert et al 2013): The
  International Genomics of Alzheimer’s Project (IGAP) is a meta-analysis of 4
  previously published GWAS datasets: the European Alzheimer’s Disease Imitative
  (EADI), the Alzheimer Disease Genetics Consortium (ADGC), Cohorts for Heart
  and Aging Research in Genomic Epidemiology (CHARGE), and Genetic and Environmental
  Risk in AD (GERAD) and includes a sample of 17,008 LOAD cases and 37,154
  cognitively normal elder controls. Participants in IGAP were of European ancestry,
  the average age was 71 and 58.4% of participants were women."
TraitCode_2: load
TraitClump_2: None
