## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/load_config/mvpa_config.yaml
# snakemake -s bmr.smk --configfile 3_Scripts/load_config/mvpa_config.yaml
DataIn: 2_DerivedData/
TraitName: Moderate-to-vigorous PA
TraitBlurb: "***Moderate-to-vigorous PA (MVPA)*** [Klimentidis et al Int J Obes 2018](https://www.nature.com/articles/s41366-018-0120-3):
  We used data from the UK Biobank to perform the largest genome-wide association
  study of PA to date, using three measures based on self-report (n = 377,234)
  and two measures based on wrist-worn accelerometry data (nmax = 91,084). MVPA Was
  calculated by taking the sum of total minutes/week of MPA multiplied by four
  and the total number of VPA minutes/week multiplied by eight, corresponding to
  their metabolic equivalents, as previously described."
TraitCode: mvpa
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
